### ISSUE TITLE
0 除算が発生している？

### ISSUE THREAD

**Issue by potato167** [tomerun/ahc_point_race#1]
src/ahc_pointrace.cr 58 行目で sum/(コンテストの数 - writer) をしていて、全てのコンテストで writer をしていたら 0 除算が発生すると思っています。
年始に wata さん以外の人が writer をしたら発生するかもしれないので報告しておきます。

**Comment by tomerun** [comment]
ありがとうございます。確かにそうですね。修正しました e97ec04
